In [1]:
import numpy as np
import sortednp as snp
from cykhash import Int64Set
import heapq
import random
import time

In [2]:
arrs = [np.array(sorted([int(random.random()*10**6) for _ in range(10**5)])) for _ in range(10)]
arrs

[array([    13,     25,     33, ..., 999943, 999956, 999967]),
 array([    12,     19,     20, ..., 999998, 999998, 999999]),
 array([    19,     19,     20, ..., 999958, 999961, 999973]),
 array([     4,     15,     19, ..., 999995, 999998, 999999]),
 array([     1,      3,      7, ..., 999965, 999982, 999998]),
 array([     8,     23,     23, ..., 999973, 999991, 999995]),
 array([     6,      8,     13, ..., 999978, 999981, 999983]),
 array([     4,     11,     30, ..., 999989, 999995, 999999]),
 array([     1,     28,     39, ..., 999972, 999979, 999993]),
 array([    16,     33,     37, ..., 999984, 999984, 999996])]

In [3]:
%%timeit -r 5 -n 5
snp.kway_merge(*arrs, assume_sorted=True, duplicates=snp.DROP)

25.9 ms ± 1.36 ms per loop (mean ± std. dev. of 5 runs, 5 loops each)


In [4]:
snp.kway_merge(*arrs, assume_sorted=True, duplicates=snp.DROP)

array([     1,      3,      4, ..., 999996, 999998, 999999])

In [5]:
%%timeit -r 5 -n 5
list(heapq.merge(*arrs))

375 ms ± 2.44 ms per loop (mean ± std. dev. of 5 runs, 5 loops each)


In [6]:
%%timeit -r 5 -n 5

np.unique(np.concatenate(arrs))

38.1 ms ± 964 µs per loop (mean ± std. dev. of 5 runs, 5 loops each)


In [7]:
%%timeit -r 5 -n 5

tot = np.array([])
for arr in arrs:
    tot = np.union1d(arr, tot)

138 ms ± 2.23 ms per loop (mean ± std. dev. of 5 runs, 5 loops each)


In [8]:
cyksets = [Int64Set(arr) for arr in arrs]


In [9]:
%%timeit -r 5 -n 5
tot = Int64Set()
for s in cyksets:
    tot = s.union(tot)

314 ms ± 2.61 ms per loop (mean ± std. dev. of 5 runs, 5 loops each)


In [10]:
sets = [set(arr) for arr in arrs]

In [11]:
%%timeit -r 5 -n 5
tot = set()
for s in sets:
    tot = s.union(tot)

198 ms ± 3.46 ms per loop (mean ± std. dev. of 5 runs, 5 loops each)
